#!/usr/bin/env python3
"""MAP.md generator seed -- the generated index is the "vector store".

Stdlib-only: `python scripts/dev/gen_map.py [repo-root]` (default root: current
directory; writes `<root>/MAP.md`). Hand-editing MAP.md is forbidden -- edit SEED and
re-run.

Structural freshness comes from scanning; the one-line responsibility strings live in
SEED. A directory on disk but absent from SEED is flagged (stderr + exit 1) so its row
gets added; a SEED row whose directory is gone is flagged the same way. A stale index
is worse than none -- the flags are the point.
"""

from __future__ import annotations

import sys
from pathlib import Path

# ---- CONFIG (the only part meant to be edited per project) -------------------
SEED = {  # module directory -> one-line responsibility (glossary terms only)
    "briefs": "Active doctrines, live briefs, ledgers (L2 state)",
    "contracts": "Cross-tier contracts + test vectors (the parallel boundary)",
    "docs": "Conventions, domain facts, runbooks, guides",
    "scripts": "dev / verify / release / audit entry points",
}
IGNORE = {"node_modules", "dist", "build", "target", "__pycache__", ".venv", "venv"}
MAX_KEY_FILES = 6  # per module; the map locates, the directory enumerates
# ------------------------------------------------------------------------------


def key_files(module: Path) -> str:
    names = sorted(p.name for p in module.iterdir() if p.is_file())
    names.sort(key=lambda n: (n != "README.md",))  # a readme leads if present
    shown = names[:MAX_KEY_FILES]
    if len(names) > MAX_KEY_FILES:
        shown.append("...")
    return " · ".join(shown) if shown else "(directories only)"


def main() -> int:
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
    on_disk = {
        p.name
        for p in root.iterdir()
        if p.is_dir() and p.name not in IGNORE and not p.name.startswith(".")
    }
    unregistered = sorted(on_disk - set(SEED))
    stale_seed = sorted(set(SEED) - on_disk)

    lines = [
        "# MAP — generated repo map",
        "",
        "<!-- GENERATED by scripts/dev/gen_map.py — hand-editing forbidden;",
        "     edit its SEED table and re-run. -->",
        "",
        "| module | responsibility | key files |",
        "|---|---|---|",
    ]
    for name in sorted(SEED):
        if name in on_disk:
            lines.append(f"| `{name}/` | {SEED[name]} | {key_files(root / name)} |")
    if unregistered:
        lines += ["", "## UNREGISTERED (add a SEED row, or archive the directory)", ""]
        lines += [f"- `{name}/`" for name in unregistered]
    (root / "MAP.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    for name in unregistered:
        print(f"UNREGISTERED: {name}/ (on disk, no SEED row)", file=sys.stderr)
    for name in stale_seed:
        print(f"STALE SEED: {name}/ (SEED row, not on disk)", file=sys.stderr)
    status = "FLAGGED" if (unregistered or stale_seed) else "OK"
    print(f"{status}: MAP.md written, {len(unregistered)} unregistered, {len(stale_seed)} stale")
    return 1 if (unregistered or stale_seed) else 0


if __name__ == "__main__":
    sys.exit(main())
